name: Publish on GitHub Pages

uses: crazy-max/ghaction-github-pages@v2.5.0

on:
  push:
  branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: npm run build

      - name: Publish
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          build_dir: dist
